image: Script  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: on  # отключаем встроенную в appveyor систему сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования